[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["LentMyc"]
solc_version="0.8.13"

[profile.default.fuzz]
runs = 256

[profile.ci.fuzz]
runs = 1_000
max_global_rejects = 200_000
[profile.ci]
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
rpc = "${RPC_URL}"